#!/usr/bin/env python3
"""
NanoDB Data Generator - TPC-H Style
Generates customer, orders, lineitem CSV previews for reference.
The actual data is generated in C++ by main.cpp.
"""

import random
import os
import csv

random.seed(42)

SEGMENTS    = ["AUTOMOBILE","BUILDING","FURNITURE","HOUSEHOLD","MACHINERY"]
STATUSES    = ["O","F","P"]
PRIORITIES  = ["1-URGENT","2-HIGH","3-MEDIUM","4-NOT SPECIFIED","5-LOW"]
FLAGS       = ["R","A","N"]

def rand_date(y0=1992, y1=1998):
    y = random.randint(y0, y1)
    m = random.randint(1, 12)
    d = random.randint(1, 28)
    return f"{y:04d}-{m:02d}-{d:02d}"

def generate_customers(n=100):
    rows = []
    for i in range(1, n+1):
        rows.append([
            i,
            f"Customer#{i:09d}",
            f"Addr{random.randint(1000,9999)}",
            random.randint(0,24),
            f"{random.randint(10,99)}-{random.randint(100,999)}-{random.randint(100,999)}-{random.randint(1000,9999)}",
            round(random.uniform(-999.99, 9999.99), 2),
            random.choice(SEGMENTS),
        ])
    return rows

def generate_orders(n=150, num_cust=100):
    rows = []
    for i in range(1, n+1):
        rows.append([
            i,
            random.randint(1, num_cust),
            random.choice(STATUSES),
            round(random.uniform(1000, 500000), 2),
            rand_date(),
            random.choice(PRIORITIES),
        ])
    return rows

def generate_lineitems(n=200, num_orders=150):
    rows = []
    for i in range(n):
        qty   = round(random.uniform(1, 50), 2)
        price = round(qty * random.uniform(10, 900), 2)
        rows.append([
            random.randint(1, num_orders),
            random.randint(1, 200000),
            random.randint(1, 10000),
            random.randint(1, 7),
            qty, price,
            round(random.uniform(0, 0.10), 4),
            round(random.uniform(0, 0.08), 4),
            random.choice(FLAGS),
            rand_date(),
        ])
    return rows

def write_csv(path, headers, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(headers)
        w.writerows(rows)
    print(f"Written: {path} ({len(rows)} rows)")

if __name__ == "__main__":
    write_csv("data/customer_preview.csv",
        ["c_custkey","c_name","c_address","c_nationkey","c_phone","c_acctbal","c_mktsegment"],
        generate_customers(100))

    write_csv("data/orders_preview.csv",
        ["o_orderkey","o_custkey","o_orderstatus","o_totalprice","o_orderdate","o_orderpriority"],
        generate_orders(150, 100))

    write_csv("data/lineitem_preview.csv",
        ["l_orderkey","l_partkey","l_suppkey","l_linenumber","l_quantity","l_extendedprice",
         "l_discount","l_tax","l_returnflag","l_shipdate"],
        generate_lineitems(200, 150))

    print("\nNote: Full dataset (20k/30k/50k rows) is generated by the C++ engine.")
    print("Run: make && ./nanodb")
